.include "Makefile.common"

$(PROG_NAME)	:	$(OBJS)
	cc $(CFLAGS) -o $@ $(.ALLSRC)

$(OBJS)		:	*.h

.c.o		:
	$(CC) $(CFLAGS)	-c $(.IMPSRC)

clear		:
	rm $(PROG_NAME) $(OBJS)

lines 		: 
	cat *.h *.c | cat -b
